config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  resources :trackings
  # get 'home/second'
  root 'trackings#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trackings

end

app/models/tracking.rb
class Tracking < ApplicationRecord
	belongs_to :teacher
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  before_action :set_tracking, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_teacher!, except: [:index, :show]
  before_action :correct_teacher, only: [:edit, :update, :destroy]
  # GET /trackings
  # GET /trackings.json
  def index
    @trackings = Tracking.all
  end

  # GET /trackings/1
  # GET /trackings/1.json
  def show
  end

  # GET /trackings/new
  def new
    @tracking = current_teacher.trackings.build
  end

  # GET /trackings/1/edit
  def edit
  end

  # POST /trackings
  # POST /trackings.json
  def create
    @tracking = current_teacher.trackings.build(tracking_params)

    respond_to do |format|
      if @tracking.save
        format.html { redirect_to @tracking, notice: 'Tracking was successfully created.' }
        format.json { render :show, status: :created, location: @tracking }
      else
        format.html { render :new }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackings/1
  # PATCH/PUT /trackings/1.json
  def update
    respond_to do |format|
      if @tracking.update(tracking_params)
        format.html { redirect_to @tracking, notice: 'Tracking was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracking }
      else
        format.html { render :edit }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackings/1
  # DELETE /trackings/1.json
  def destroy
    @tracking.destroy
    respond_to do |format|
      format.html { redirect_to trackings_url, notice: 'Tracking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_teacher
    @tracking = current_teacher.trackings.find_by(id: params[:id])
    redirect_to trackings_path, notice: "You're not authorized for this action!" if @tracking.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracking
      @tracking = Tracking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tracking_params
      params.require(:tracking).permit(:first_name, :last_name, :user_name, :date, :clock_in_out, :clock_time, :teacher_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Clock Management', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if teacher_signed_in? %>
          <li class="nav-item">
  				<%= link_to 'Add Tracking', new_tracking_path, class:"nav-link" %>
        	</li>
        	<li class="nav-item">
  				<%= link_to 'Edit Profile', edit_teacher_registration_path, class:"nav-link" %>
        	</li>
	        <li class="nav-item">
	        </li>
	    <% else %>
	        <li class="nav-item">
	  			<%= link_to 'Sign Up', new_teacher_registration_path, class:"nav-link" %>
	        </li>
	        <li class="nav-item">
	  			<%= link_to 'Log In', new_teacher_session_path, class:"nav-link" %>
	        </li>
	    <% end %>

      </ul>
      <% if teacher_signed_in? %>
	        <span class="card"> <%= current_teacher.email %></span>
	        <span> <%= link_to 'Sign Out', destroy_teacher_session_path, method: :delete, class:"nav-link" %> </span>
	  <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h3>Clock Management Application</h3>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Clockmanagement</title>
        <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/trackings/_form.html.erb
<%= form_with(model: tracking) do |form| %>
  <% if tracking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tracking.errors.count, "error") %> prohibited this tracking from being saved:</h2>

      <ul>
        <% tracking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <% form.label :first_name, class:"form-label" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name", :required => true %>
  </div>

  <div class="field mb-3">
    <% form.label :last_name, class:"form-label" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name", :required => true %>
  </div>

  <div class="field mb-3">
    <% form.label :user_name, class:"form-label" %>
    <%= form.text_field :user_name, class:"form-control", placeholder:"Username", :required => true %>
  </div>

  <div class="field mb-3">
    <% form.label :teacher_id, class:"form-label" %>
    <%= form.number_field :teacher_id, id: :tracking_teacher_id, class:"form-control", value: current_teacher.id, type: :hidden %>
  </div>

  <div class="field mb-3 col-md-6">
    <% form.label :date, as: :string, class:"form-label" %>
    <%= form.date_select :date, class:"form-select", :required => true %>
  </div>

  <div class="field mb-3">
    <% form.label :clock_in_out, class:"form-label" %>
    <%= form.text_field :clock_in_out, class:"form-control", placeholder:"In/Out", :required => true %>
  </div>

  <div class="field mb-3 col-md-6">
    <% form.label :clock_time, class:"form-label" %>
    <%= form.time_select :clock_time, class: "form-select", :required => true %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>

<% end %>

app/views/trackings/edit.html.erb
<br/>
<h1>Editing Tracking</h1>
<br/>

<%= render 'form', tracking: @tracking %>
<br/>

<%= link_to 'Show', @tracking, class:"btn btn-secondary" %>
<%= link_to 'Back', trackings_path, class:"btn btn-secondary" %>
<%= link_to 'Delete', @tracking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %>
<br/><br/>

app/views/trackings/index.html.erb
<% if teacher_signed_in? %>
  <h1>Trackings</h1>
  <table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Username</th>
        <th>Date</th>
        <th>Clock in out</th>
        <th>Clock time</th>
        <th>Teacher ID</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @trackings.each do |tracking| %>
        <% if tracking.teacher == current_teacher %>
          <tr>
            <td><%= link_to  tracking.first_name + '' + tracking.last_name, tracking, class: "link-info" %></td>
            <td><%= tracking.user_name %></td>
            <td><%= tracking.date %></td>
            <td><%= tracking.clock_in_out %></td>
            <td><%= tracking.clock_time.strftime("%I:%M%p") %></td>
            <td><%= tracking.teacher_id %></td>
            <td><%= link_to 'Edit', edit_tracking_path(tracking), class: "btn btn-outline-primary" %></td>
            <td><%= link_to 'Delete', tracking, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Tracking', new_tracking_path, class:"btn btn-secondary" %>
<% else %>
  <h3>Clock Management Application</h3>
  <br/>
  <ul class="list-unstyled">
    <li>I used devise https://github.com/heartcombo/devise for implementing the teacher authentication.
The teacher can:
      <ul>
        <li>create a new profile/ sign up</li>
        <li>modify/update the profile</li>
        <li>delete the profile</li>
        <li>log in/sign out</li>
        <li>the log in and sign up are only possible for the teachers that are not already signed in </li>
        <li>the sign out and edit profile is only possible for the teachers that are already signed in </li>
      </ul>
  </li>
  <br/>

  <li>Once the teacher logged in to the Clock Management Application
    <ul>
      <li>they can create new trackings (clock in or clock out) </li>
      <li>they can modify trackings (clock in or clock out) </li>
      <li>they can show the trackings (view the information) </li>
      <li>they only have access to their own trackings </li>
      <li>they cannot modify other teachers trackings </li>
      <li>if they attempt to modify/delete a record while they are not logged in they will be redirected to log in page </li>
      <li>they can delete trackings (clock in or clock out entries) </li>
      <li>they can view the list of their trackings </li>
    </ul>
  </li>
  <br/>

  <li>The database schema is very simple has two table teachers and trackings
each teacher has many trackings and each tracking belongs to a teacher
the foreign key on trackings table is teacher_id
the primary key of teachers table is id and is the id </li>
  <br/>

  <li>If I work another day on this application I'd:
    <ul>
      <li>add more validations on the data inserted by the user </li>
      <li>add date picker on the view for selecting time and date </li>
      <li>modify the data format for storing time in db </li>
      <li>modify the time/date to be shown in clients timezone instead of utc </li>
      <li>they cannot modify other teachers trackings </li>
      <li>modify the db schema for each clock in I'd consider a clock out so each tracking would have both clock in/clock out events so I could only let the teacher to insert valid data (ex. I'd check if the associated clock in time is less than clock out or if there is already a clock in for the clock out event ..) </li>
    </ul>
  </li>
  <br/>

  <li>If I work another day on this application I'd:
    <ul>
      <li>still work on improving the design </li>
      <li>add more checks and validations </li>
      <li>add more features to the application such as:
        <ul>
          <li>calculating the duration of each tracking </li>
          <li>add a description section to db and to the forms so the user can assign a description to the tracking event </li>
          <li>add a feature so the user can insert a new event only by clicking a button, lets press a button which will take the now time and automatically creates a new event for the user  </li>
          <li>improve the db schema and model and remove the unesessary fields from the view </li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
  <br/>

<% end %>

app/views/trackings/new.html.erb
<br/>
<h1>Add New Tracking</h1>
<br/>
<%= render 'form', tracking: @tracking %>
<br/>
<%= link_to 'Back', trackings_path, class:"btn btn-secondary" %>
<br/><br/>

app/views/trackings/show.html.erb
<div class="card text-center">
  <div class="card-header bg-dark text-white">
    <%= @tracking.first_name %> <%= @tracking.last_name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"></h5>
    <p>
      <strong>Username:</strong>
      <%= @tracking.user_name %>
    </p>
    <p>
      <strong>Clock In/Out:</strong>
      <%= @tracking.clock_in_out %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @tracking.date %>
    </p>

    <p>
      <strong>Time:</strong>
      <%= @tracking.clock_time.strftime("%I:%M%p") %>
    </p>

    <%= link_to 'Edit', edit_tracking_path(@tracking), class:"btn btn-secondary" %>
    <%= link_to 'Back', trackings_path, class:"btn btn-secondary" %>

  </div>
</div>